name = "toss"
version = "1.0.0-rc4"

description = "A UDP client for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "sbergen", repo = "toss" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
glip = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
checkmark = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
